### ISSUE TITLE
pip install not working consistently

### ISSUE THREAD

**Issue by psurya1994** [TMElyralab/MMCM#3]
After I create a fresh environment, when I install the repo with pip install I get the following issue. But when I just pip install again (for the second time), the issue doesn't happen anymore. why could this be? 

setup commands used:
```
conda create --name musev python=3.10 -y
conda activate musev
pip install git+https://github.com/TMElyralab/MMCM.git@setup
```
error logs:
```
Collecting git+https://github.com/TMElyralab/MMCM.git@setup
  Cloning https://github.com/TMElyralab/MMCM.git (to revision setup) to /tmp/pip-req-build-neroapfy
  Running command git clone --filter=blob:none --quiet https://github.com/TMElyralab/MMCM.git /tmp/pip-req-build-neroapfy
  Running command git checkout -b setup --track origin/setup
  Switched to a new branch 'setup'
  Branch 'setup' set up to track remote branch 'setup' from 'origin'.
  Resolved https://github.com/TMElyralab/MMCM.git to commit ff9be8759e866e09532ca79bb87f4422461166d0
  Preparing metadata (setup.py) ... done
  WARNING: No metadata found in /tmp/pip-pip-egg-info-th7qxtaa
ERROR: Exception:
Traceback (most recent call last):
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 595, in prepare_metadata
    self._set_requirement()
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 398, in _set_requirement
    if isinstance(parse_version(self.metadata["Version"]), Version):
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/surya/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by psurya1994** [comment]
I've debugged this further and the issue arises because invoking subprocess calls to pip and mim within setup.py. It can create a number of potential problems, particularly during the metadata preparation step that pip performs during installation.
```
result = subprocess.run(
    ["pip", "install", "--no-cache-dir", "-U", "openmim"],
    capture_output=True,
    text=True,
)
result = subprocess.run(["mim", "install", "mmengine"], capture_output=True, text=True)
result = subprocess.run(
    ["mim", "install", "mmcv>=2.0.1"], capture_output=True, text=True
)
result = subprocess.run(
    ["mim", "install", "mmdet>=3.1.0"], capture_output=True, text=True
)
result = subprocess.run(
    ["mim", "install", "mmpose>=1.1.0"], capture_output=True, text=True
)
```
